[package]
name = "uc-hub-client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-nats = "0"
async-trait = "0"
base64 = "0"
bytes = "1"
const_format = "0.2"
flatbuffers = { version="23", features = ["serde", "serialize"]}
futures = "0"
futures-util = "0"
hyper = "1"
reqwest = { version = "0", features = ["json", "rustls-tls"], default-features = false  }
regex = "1"
serde = "1"
tokio = { version = "1", features = ["rt-multi-thread"] }
tracing = "0"
thiserror = "1"
urlencoding = "2"

[dev-dependencies]
serial_test = "3"
rstest = "0"
