[package]
name = "u-os-hub-client"
description = "u-OS Data Hub Client"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-nats = "0.37"
async-trait = "0"
base64 = "0"
bytes = "1"
const_format = "0.2"
flatbuffers = { version="23", features = ["serde", "serialize"]}
futures = "0"
futures-util = "0"
hyper = "1"
reqwest = { version = "0", features = ["json", "rustls-tls"], default-features = false  }
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread"] }
tracing = "0"
thiserror = "1"
urlencoding = "2"
rustc-hash = "2.1"

[dev-dependencies]
serial_test = "3"
rstest = "0"
tracing-subscriber = { version = "0.3", features = ["fmt"] }
clap = { version = "4", features = ["derive"] }
