# SPDX-FileCopyrightText: 2025 Weidmueller Interface GmbH & Co. KG <oss@weidmueller.com>
#
# SPDX-License-Identifier: MIT

# This allows some lints in unit tests
# Unfortunately this doesnt work for integration tests, so we use explicit allow tags there.
allow-unwrap-in-tests = true
allow-expect-in-tests = true
