// SPDX-FileCopyrightText: 2025 Weidmueller Interface GmbH & Co. KG <oss@weidmueller.com>
//
// SPDX-License-Identifier: MIT

= Contributing

Thank you for your interest in contributing to this project!

You can contribute in many ways, including:

- Reporting bugs
- Suggesting features
- Writing code or documentation

== Conduct

Please follow the link:CODE_OF_CONDUCT.md[Code of Conduct]. This describes the minimum behavior expected from all contributors.

== Reporting Bugs and Suggesting Features

Please use the GitHub issue tracker for reporting bugs and suggesting features.

== Writing Code or Documentation

For contributing source files, please fork the repository and create a pull request (PR) from your fork to the main repository.

This adheres to the standard GitHub open source workflow. For details, see link:https://docs.github.com/en/get-started/quickstart/contributing-to-projects[Contributing to Projects on GitHub].

The project is optimized for development within a VSCode devcontainer.

=== Developing in Visual Studio Code

Install `Remote Development` and `Remote-Containers` and start the development container via `Reopen in Container`.

==== Set Up Pre-commit Hooks (Optional)

This repository uses prek for pre-commit hooks.

Run `prek install` while in the devcontainer to set up the hooks locally.

==== Building

Clone the submodules:

----
git submodule update --init
----

Now you can build the project via

```sh
cargo build
```

==== Run tests

You can run all tests via

```sh
cargo test
```

==== Generate documentation

You can generate the crate documentation via

```sh
cargo doc
```

Then you will find the documentation under `target/doc/u_os_hub_client/index.html`.

==== Running examples

The examples folder contains some examples of how to use the library.
Running the examples requires a running u-OS Data Hub instance as well as a nats server and various authentication services.

The easiest way to do this is to cross compile the examples and run them directly on the target device.

There are convenience scripts to deploy and remove the examples from a device:

```bash
#Cross compiles and installs examples as systemd services on the target device
./tools/build_and_deploy_hub_examples.sh <IP> <arch>

#Removes the examples from the target device
./tools/remove_hub_examples.sh <IP>
```


=== Publishing Your Changes

==== Developer Certificate of Origin

All commits must be signed off to affirm compliance with the link:https://developercertificate.org/[DCO].

==== Check Your Changes

Before creating a merge request, please run `tools/check-merge-request.sh` to validate your changes. This will prevent failures in the CI pipeline later.
