= u-OS Data Hub - Rust Client 🦀
:toc:

== Introduction

This is the u-OS Data Hub client library.
The focus of this library is high performance.

This library primary contains:

- Provider Handling
- Consumer Handling (currently not implemented)
- The generated flatbuffers of the Variable-NATS-API

== Maintainers

This project is currently maintained by:

- Etienne Schmidt (w011279)
- Christian Peters (w011238)
- Kristina Henning (w011985)

Please contact the persons above for merge requests or any questions regarding this repository.

== How to add this crate to your cargo project

You just need to add the following to your Cargo.toml and update the hash of the latest commit.
// TODO: Add github url until it exists
```toml
[dependencies]
u-os-hub-client = { git = "https://srvde554.weidmueller.com/gitlab/u-control/uc-hub-client-rs.git", rev = "LATEST_HASH" }
```

== Getting started

First clone the submodules:

----
git submodule update --init
----

=== Development

We use a link:https://containers.dev/implementors/spec/[development container] for development within this repository.
Other containers are also started.
See the file link:.devcontainer/docker-compose.devcontainer.yaml[docker-compose.devcontainer.yaml] for details.

In VS code, press `F1` and select `Dev Containers: Reopen in container` to start the development container.

==== Regenerate flatbuffers

```sh
./tools/regenerate_fbs.sh
```

==== Generate documentation

You can generate the crate documentation via

```sh
cargo doc
```

Then you will find the documentation under `target/doc/u_os_hub_client/index.html`.

==== Run tests

You can run all tests via

```sh
cargo test
```

==== Check merge request before creating it

Before issuing a merge request, you can locally simulate all pipeline checks by running

```sh
./tools/check_merge_request.sh
```

This will build, lint, create docs and run audit and unit tests.
