// SPDX-FileCopyrightText: 2025 Weidmueller Interface GmbH & Co. KG <oss@weidmueller.com>
//
// SPDX-License-Identifier: MIT

= u-OS Data Hub - Rust Client 🦀
:toc:

== Introduction

Welcome to the u-OS Data Hub client library.

This library allows to interact with the u-OS Variable Data Hub as a provider or consumer.

== How to add this crate to your cargo project

Add the following to your Cargo.toml and update the hash of the latest commit.

```toml
[dependencies]
u-os-hub-client = { git = "https://github.com/weidmueller/u-os-hub-client-rs.git", rev = "LATEST_HASH" }
```

== Examples

The `examples` folder contains some examples of how to use the library.

See link:CONTRIBUTING.adoc[CONTRIBUTING.adoc] if you want to build and run them.

== Questions / Issues / Contributions

If you have any questions or need help, please visit the link:https://support.weidmueller.com/support-center/[Weidmueller Support Center].

If you would like to contribute to the project, please take a look at our link:CONTRIBUTING.adoc[Contributing Guidelines].

== License

This project is licensed under the link:LICENSE[MIT license].
